# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11NlSZwMiYRVH35CGW01sNb1YlJ_7k6-6
"""

import pandas as pd
import json
import matplotlib.pyplot as plt
import seaborn as sns

data = []

with open('/content/News_Category_Dataset_v3.json', 'r') as f:
    for line in f:
        data.append(json.loads(line))

df = pd.DataFrame(data)

df.head()

df.info()

df.isnull().sum()

df['category'].value_counts()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
df['category'].value_counts().head(10).plot(kind='bar')
plt.title("Top 10 Categories")
plt.xlabel("Category")
plt.ylabel("Count")
plt.xticks(rotation=45)
plt.show()

df['text'] = df['headline'] + " " + df['short_description']

df['length'] = df['text'].apply(lambda x: len(str(x).split()))

plt.hist(df['length'], bins=50)
plt.title("Text Length Distribution")
plt.xlabel("Number of words")
plt.ylabel("Count")
plt.show()

import re

def clean_text(text):
    text = str(text).lower()  # viết thường
    text = re.sub(r'http\S+', '', text)  # bỏ link
    text = re.sub(r'[^a-zA-Z\s]', '', text)  # bỏ ký tự đặc biệt
    return text

df['clean_text'] = df['text'].apply(clean_text)

df[['text', 'clean_text']].head()

df['tokens'] = df['clean_text'].apply(lambda x: x.split())

df[['clean_text', 'tokens']].head()

import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))

df['tokens'] = df['tokens'].apply(
    lambda x: [word for word in x if word not in stop_words]
)

df[['clean_text', 'tokens']].head()

df['processed_text'] = df['tokens'].apply(lambda x: " ".join(x))

df[['tokens', 'processed_text']].head()